### ISSUE TITLE
css attribute ‘z-index’ can't compile correctly

### ISSUE THREAD

**Issue by shenxiang11** [tnottu/less-autocompile#8]
I set z-index to 1000 but compiled 1.
I use the less-postcss-autocompile in ATOM

**Comment by tarodspj** [comment]
Same problem z-index from 100 to 6

**Comment by tnottu** [comment]
This is because of the "z-index rebasing" option in cssnano. See issue #7, there is a workaround for this.

**Comment by tarodspj** [comment]
Thx Tnottu
